// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0
// source: svc/admin/admin.ext.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminExtClient is the client API for AdminExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminExtClient interface {
	AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginRsp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserRsp, error)
}

type adminExtClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminExtClient(cc grpc.ClientConnInterface) AdminExtClient {
	return &adminExtClient{cc}
}

func (c *adminExtClient) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginRsp, error) {
	out := new(AdminLoginRsp)
	err := c.cc.Invoke(ctx, "/svc.admin.AdminExt/AdminLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminExtClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserRsp, error) {
	out := new(GetUserRsp)
	err := c.cc.Invoke(ctx, "/svc.admin.AdminExt/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminExtServer is the server API for AdminExt service.
// All implementations should embed UnimplementedAdminExtServer
// for forward compatibility
type AdminExtServer interface {
	AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginRsp, error)
	GetUser(context.Context, *GetUserReq) (*GetUserRsp, error)
}

// UnimplementedAdminExtServer should be embedded to have forward compatible implementations.
type UnimplementedAdminExtServer struct {
}

func (UnimplementedAdminExtServer) AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLogin not implemented")
}
func (UnimplementedAdminExtServer) GetUser(context.Context, *GetUserReq) (*GetUserRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

// UnsafeAdminExtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminExtServer will
// result in compilation errors.
type UnsafeAdminExtServer interface {
	mustEmbedUnimplementedAdminExtServer()
}

func RegisterAdminExtServer(s grpc.ServiceRegistrar, srv AdminExtServer) {
	s.RegisterService(&AdminExt_ServiceDesc, srv)
}

func _AdminExt_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminExtServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.admin.AdminExt/AdminLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminExtServer).AdminLogin(ctx, req.(*AdminLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminExt_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminExtServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.admin.AdminExt/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminExtServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminExt_ServiceDesc is the grpc.ServiceDesc for AdminExt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminExt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svc.admin.AdminExt",
	HandlerType: (*AdminExtServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLogin",
			Handler:    _AdminExt_AdminLogin_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AdminExt_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc/admin/admin.ext.proto",
}
