// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0
// source: svc/admin/admin.ext.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminSvcClient is the client API for AdminSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminSvcClient interface {
	AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginRsp, error)
}

type adminSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminSvcClient(cc grpc.ClientConnInterface) AdminSvcClient {
	return &adminSvcClient{cc}
}

func (c *adminSvcClient) AdminLogin(ctx context.Context, in *AdminLoginReq, opts ...grpc.CallOption) (*AdminLoginRsp, error) {
	out := new(AdminLoginRsp)
	err := c.cc.Invoke(ctx, "/proto.svc.admin.AdminSvc/AdminLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminSvcServer is the server API for AdminSvc service.
// All implementations should embed UnimplementedAdminSvcServer
// for forward compatibility
type AdminSvcServer interface {
	AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginRsp, error)
}

// UnimplementedAdminSvcServer should be embedded to have forward compatible implementations.
type UnimplementedAdminSvcServer struct {
}

func (UnimplementedAdminSvcServer) AdminLogin(context.Context, *AdminLoginReq) (*AdminLoginRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminLogin not implemented")
}

// UnsafeAdminSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminSvcServer will
// result in compilation errors.
type UnsafeAdminSvcServer interface {
	mustEmbedUnimplementedAdminSvcServer()
}

func RegisterAdminSvcServer(s grpc.ServiceRegistrar, srv AdminSvcServer) {
	s.RegisterService(&AdminSvc_ServiceDesc, srv)
}

func _AdminSvc_AdminLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminSvcServer).AdminLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.svc.admin.AdminSvc/AdminLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminSvcServer).AdminLogin(ctx, req.(*AdminLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminSvc_ServiceDesc is the grpc.ServiceDesc for AdminSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.svc.admin.AdminSvc",
	HandlerType: (*AdminSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminLogin",
			Handler:    _AdminSvc_AdminLogin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc/admin/admin.ext.proto",
}
