// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: svc/admin/admin.ext.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	svc "microsvc/protocol/svc"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base     *svc.AdminBaseReq `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Username int64             `protobuf:"varint,2,opt,name=username,proto3" json:"username,omitempty"`
	Password string            `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AdminLoginReq) Reset() {
	*x = AdminLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_admin_admin_ext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginReq) ProtoMessage() {}

func (x *AdminLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_svc_admin_admin_ext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginReq.ProtoReflect.Descriptor instead.
func (*AdminLoginReq) Descriptor() ([]byte, []int) {
	return file_svc_admin_admin_ext_proto_rawDescGZIP(), []int{0}
}

func (x *AdminLoginReq) GetBase() *svc.AdminBaseReq {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *AdminLoginReq) GetUsername() int64 {
	if x != nil {
		return x.Username
	}
	return 0
}

func (x *AdminLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 这个结构体会写入 svc.AdminRsp.data, 具体参考代码
type AdminLoginRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string        `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserInfo *LoginResBody `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
}

func (x *AdminLoginRsp) Reset() {
	*x = AdminLoginRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_admin_admin_ext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminLoginRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminLoginRsp) ProtoMessage() {}

func (x *AdminLoginRsp) ProtoReflect() protoreflect.Message {
	mi := &file_svc_admin_admin_ext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminLoginRsp.ProtoReflect.Descriptor instead.
func (*AdminLoginRsp) Descriptor() ([]byte, []int) {
	return file_svc_admin_admin_ext_proto_rawDescGZIP(), []int{1}
}

func (x *AdminLoginRsp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AdminLoginRsp) GetUserInfo() *LoginResBody {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type LoginResBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid  int64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Nick string  `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Sex  svc.Sex `protobuf:"varint,3,opt,name=sex,proto3,enum=proto.svc.Sex" json:"sex,omitempty"`
}

func (x *LoginResBody) Reset() {
	*x = LoginResBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_admin_admin_ext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResBody) ProtoMessage() {}

func (x *LoginResBody) ProtoReflect() protoreflect.Message {
	mi := &file_svc_admin_admin_ext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResBody.ProtoReflect.Descriptor instead.
func (*LoginResBody) Descriptor() ([]byte, []int) {
	return file_svc_admin_admin_ext_proto_rawDescGZIP(), []int{2}
}

func (x *LoginResBody) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginResBody) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *LoginResBody) GetSex() svc.Sex {
	if x != nil {
		return x.Sex
	}
	return svc.Sex(0)
}

var File_svc_admin_admin_ext_proto protoreflect.FileDescriptor

var file_svc_admin_admin_ext_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x76, 0x63, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x1a, 0x10, 0x73, 0x76,
	0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f,
	0x73, 0x76, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x74, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x2b, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x61, 0x0a, 0x0d, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3a, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x56, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x73, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x20,
	0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x32, 0x58, 0x0a, 0x08, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x76, 0x63, 0x12, 0x4c, 0x0a, 0x0a,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x42, 0x1d, 0x5a, 0x1b, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x73, 0x76, 0x63, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_svc_admin_admin_ext_proto_rawDescOnce sync.Once
	file_svc_admin_admin_ext_proto_rawDescData = file_svc_admin_admin_ext_proto_rawDesc
)

func file_svc_admin_admin_ext_proto_rawDescGZIP() []byte {
	file_svc_admin_admin_ext_proto_rawDescOnce.Do(func() {
		file_svc_admin_admin_ext_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_admin_admin_ext_proto_rawDescData)
	})
	return file_svc_admin_admin_ext_proto_rawDescData
}

var file_svc_admin_admin_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_svc_admin_admin_ext_proto_goTypes = []interface{}{
	(*AdminLoginReq)(nil),    // 0: proto.svc.admin.AdminLoginReq
	(*AdminLoginRsp)(nil),    // 1: proto.svc.admin.AdminLoginRsp
	(*LoginResBody)(nil),     // 2: proto.svc.admin.LoginResBody
	(*svc.AdminBaseReq)(nil), // 3: proto.svc.AdminBaseReq
	(svc.Sex)(0),             // 4: proto.svc.Sex
}
var file_svc_admin_admin_ext_proto_depIdxs = []int32{
	3, // 0: proto.svc.admin.AdminLoginReq.base:type_name -> proto.svc.AdminBaseReq
	2, // 1: proto.svc.admin.AdminLoginRsp.user_info:type_name -> proto.svc.admin.LoginResBody
	4, // 2: proto.svc.admin.LoginResBody.sex:type_name -> proto.svc.Sex
	0, // 3: proto.svc.admin.AdminSvc.AdminLogin:input_type -> proto.svc.admin.AdminLoginReq
	1, // 4: proto.svc.admin.AdminSvc.AdminLogin:output_type -> proto.svc.admin.AdminLoginRsp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_svc_admin_admin_ext_proto_init() }
func file_svc_admin_admin_ext_proto_init() {
	if File_svc_admin_admin_ext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_admin_admin_ext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_admin_admin_ext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminLoginRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_admin_admin_ext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_admin_admin_ext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_admin_admin_ext_proto_goTypes,
		DependencyIndexes: file_svc_admin_admin_ext_proto_depIdxs,
		MessageInfos:      file_svc_admin_admin_ext_proto_msgTypes,
	}.Build()
	File_svc_admin_admin_ext_proto = out.File
	file_svc_admin_admin_ext_proto_rawDesc = nil
	file_svc_admin_admin_ext_proto_goTypes = nil
	file_svc_admin_admin_ext_proto_depIdxs = nil
}
