// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.18.3
// source: svc/assets/assets.ext.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	svc "microsvc/protocol/svc"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserAssetsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req *svc.BaseExtReq `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Uid []int64         `protobuf:"varint,2,rep,packed,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserAssetsReq) Reset() {
	*x = GetUserAssetsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_assets_assets_ext_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserAssetsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssetsReq) ProtoMessage() {}

func (x *GetUserAssetsReq) ProtoReflect() protoreflect.Message {
	mi := &file_svc_assets_assets_ext_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssetsReq.ProtoReflect.Descriptor instead.
func (*GetUserAssetsReq) Descriptor() ([]byte, []int) {
	return file_svc_assets_assets_ext_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserAssetsReq) GetReq() *svc.BaseExtReq {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GetUserAssetsReq) GetUid() []int64 {
	if x != nil {
		return x.Uid
	}
	return nil
}

type GetUserAssetsRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Umap map[int64]*User `protobuf:"bytes,1,rep,name=umap,proto3" json:"umap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetUserAssetsRsp) Reset() {
	*x = GetUserAssetsRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_assets_assets_ext_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserAssetsRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAssetsRsp) ProtoMessage() {}

func (x *GetUserAssetsRsp) ProtoReflect() protoreflect.Message {
	mi := &file_svc_assets_assets_ext_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAssetsRsp.ProtoReflect.Descriptor instead.
func (*GetUserAssetsRsp) Descriptor() ([]byte, []int) {
	return file_svc_assets_assets_ext_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserAssetsRsp) GetUmap() map[int64]*User {
	if x != nil {
		return x.Umap
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid   int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Money int32 `protobuf:"varint,2,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_assets_assets_ext_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_svc_assets_assets_ext_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_svc_assets_assets_ext_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *User) GetMoney() int32 {
	if x != nil {
		return x.Money
	}
	return 0
}

var File_svc_assets_assets_ext_proto protoreflect.FileDescriptor

var file_svc_assets_assets_ext_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x76, 0x63, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2f, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x2e, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x1a,
	0x10, 0x73, 0x76, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x03, 0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x45, 0x78, 0x74, 0x52, 0x65, 0x71, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x22, 0xa5, 0x01, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x52, 0x73, 0x70, 0x12, 0x40, 0x0a, 0x04, 0x75, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x52, 0x73, 0x70, 0x2e, 0x55, 0x6d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x75, 0x6d, 0x61, 0x70, 0x1a, 0x4f, 0x0a, 0x09, 0x55, 0x6d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76,
	0x63, 0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2e, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x32, 0x5e, 0x0a, 0x09, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x73, 0x45, 0x78, 0x74, 0x12, 0x51, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2e, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63,
	0x2e, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x73, 0x70, 0x42, 0x1e, 0x5a, 0x1c, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x73, 0x76, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73, 0x76,
	0x63, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_assets_assets_ext_proto_rawDescOnce sync.Once
	file_svc_assets_assets_ext_proto_rawDescData = file_svc_assets_assets_ext_proto_rawDesc
)

func file_svc_assets_assets_ext_proto_rawDescGZIP() []byte {
	file_svc_assets_assets_ext_proto_rawDescOnce.Do(func() {
		file_svc_assets_assets_ext_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_assets_assets_ext_proto_rawDescData)
	})
	return file_svc_assets_assets_ext_proto_rawDescData
}

var file_svc_assets_assets_ext_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_svc_assets_assets_ext_proto_goTypes = []interface{}{
	(*GetUserAssetsReq)(nil), // 0: proto.svc.assets.GetUserAssetsReq
	(*GetUserAssetsRsp)(nil), // 1: proto.svc.assets.GetUserAssetsRsp
	(*User)(nil),             // 2: proto.svc.assets.User
	nil,                      // 3: proto.svc.assets.GetUserAssetsRsp.UmapEntry
	(*svc.BaseExtReq)(nil),   // 4: proto.svc.BaseExtReq
}
var file_svc_assets_assets_ext_proto_depIdxs = []int32{
	4, // 0: proto.svc.assets.GetUserAssetsReq.req:type_name -> proto.svc.BaseExtReq
	3, // 1: proto.svc.assets.GetUserAssetsRsp.umap:type_name -> proto.svc.assets.GetUserAssetsRsp.UmapEntry
	2, // 2: proto.svc.assets.GetUserAssetsRsp.UmapEntry.value:type_name -> proto.svc.assets.User
	0, // 3: proto.svc.assets.AssetsExt.GetUser:input_type -> proto.svc.assets.GetUserAssetsReq
	1, // 4: proto.svc.assets.AssetsExt.GetUser:output_type -> proto.svc.assets.GetUserAssetsRsp
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_svc_assets_assets_ext_proto_init() }
func file_svc_assets_assets_ext_proto_init() {
	if File_svc_assets_assets_ext_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_assets_assets_ext_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserAssetsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_assets_assets_ext_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserAssetsRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_assets_assets_ext_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_assets_assets_ext_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_assets_assets_ext_proto_goTypes,
		DependencyIndexes: file_svc_assets_assets_ext_proto_depIdxs,
		MessageInfos:      file_svc_assets_assets_ext_proto_msgTypes,
	}.Build()
	File_svc_assets_assets_ext_proto = out.File
	file_svc_assets_assets_ext_proto_rawDesc = nil
	file_svc_assets_assets_ext_proto_goTypes = nil
	file_svc_assets_assets_ext_proto_depIdxs = nil
}
