// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0
// source: svc/user/user.int.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserIntClient is the client API for UserInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserIntClient interface {
	GetUser(ctx context.Context, in *GetUserIntReq, opts ...grpc.CallOption) (*GetUserIntRsp, error)
	Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestRsp, error)
}

type userIntClient struct {
	cc grpc.ClientConnInterface
}

func NewUserIntClient(cc grpc.ClientConnInterface) UserIntClient {
	return &userIntClient{cc}
}

func (c *userIntClient) GetUser(ctx context.Context, in *GetUserIntReq, opts ...grpc.CallOption) (*GetUserIntRsp, error) {
	out := new(GetUserIntRsp)
	err := c.cc.Invoke(ctx, "/svc.user.UserInt/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userIntClient) Test(ctx context.Context, in *TestReq, opts ...grpc.CallOption) (*TestRsp, error) {
	out := new(TestRsp)
	err := c.cc.Invoke(ctx, "/svc.user.UserInt/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserIntServer is the server API for UserInt service.
// All implementations should embed UnimplementedUserIntServer
// for forward compatibility
type UserIntServer interface {
	GetUser(context.Context, *GetUserIntReq) (*GetUserIntRsp, error)
	Test(context.Context, *TestReq) (*TestRsp, error)
}

// UnimplementedUserIntServer should be embedded to have forward compatible implementations.
type UnimplementedUserIntServer struct {
}

func (UnimplementedUserIntServer) GetUser(context.Context, *GetUserIntReq) (*GetUserIntRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserIntServer) Test(context.Context, *TestReq) (*TestRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}

// UnsafeUserIntServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserIntServer will
// result in compilation errors.
type UnsafeUserIntServer interface {
	mustEmbedUnimplementedUserIntServer()
}

func RegisterUserIntServer(s grpc.ServiceRegistrar, srv UserIntServer) {
	s.RegisterService(&UserInt_ServiceDesc, srv)
}

func _UserInt_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIntReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.user.UserInt/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).GetUser(ctx, req.(*GetUserIntReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserInt_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.user.UserInt/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).Test(ctx, req.(*TestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInt_ServiceDesc is the grpc.ServiceDesc for UserInt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svc.user.UserInt",
	HandlerType: (*UserIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _UserInt_GetUser_Handler,
		},
		{
			MethodName: "Test",
			Handler:    _UserInt_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc/user/user.int.proto",
}
