POST http://localhost:8000/svc.user.UserExt/GetUser
Content-Type: application/json

{
  "uids": [1]
}

###
POST http://localhost:8000/svc.admin.AdminExt/GetUser
Content-Type: application/json

{
  "uids": [1]
}
