// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: svc/const.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sex int32

const (
	Sex_Unknown Sex = 0
	Sex_Male    Sex = 1
	Sex_Female  Sex = 2
)

// Enum value maps for Sex.
var (
	Sex_name = map[int32]string{
		0: "Unknown",
		1: "Male",
		2: "Female",
	}
	Sex_value = map[string]int32{
		"Unknown": 0,
		"Male":    1,
		"Female":  2,
	}
)

func (x Sex) Enum() *Sex {
	p := new(Sex)
	*p = x
	return p
}

func (x Sex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sex) Descriptor() protoreflect.EnumDescriptor {
	return file_svc_const_proto_enumTypes[0].Descriptor()
}

func (Sex) Type() protoreflect.EnumType {
	return &file_svc_const_proto_enumTypes[0]
}

func (x Sex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sex.Descriptor instead.
func (Sex) EnumDescriptor() ([]byte, []int) {
	return file_svc_const_proto_rawDescGZIP(), []int{0}
}

var File_svc_const_proto protoreflect.FileDescriptor

var file_svc_const_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x76, 0x63, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x76, 0x63, 0x2a, 0x28, 0x0a, 0x03,
	0x53, 0x65, 0x78, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x4d, 0x61, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x65,
	0x6d, 0x61, 0x6c, 0x65, 0x10, 0x02, 0x42, 0x17, 0x5a, 0x15, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x76, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73, 0x76, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_const_proto_rawDescOnce sync.Once
	file_svc_const_proto_rawDescData = file_svc_const_proto_rawDesc
)

func file_svc_const_proto_rawDescGZIP() []byte {
	file_svc_const_proto_rawDescOnce.Do(func() {
		file_svc_const_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_const_proto_rawDescData)
	})
	return file_svc_const_proto_rawDescData
}

var file_svc_const_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_svc_const_proto_goTypes = []interface{}{
	(Sex)(0), // 0: proto.svc.Sex
}
var file_svc_const_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svc_const_proto_init() }
func file_svc_const_proto_init() {
	if File_svc_const_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_const_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svc_const_proto_goTypes,
		DependencyIndexes: file_svc_const_proto_depIdxs,
		EnumInfos:         file_svc_const_proto_enumTypes,
	}.Build()
	File_svc_const_proto = out.File
	file_svc_const_proto_rawDesc = nil
	file_svc_const_proto_goTypes = nil
	file_svc_const_proto_depIdxs = nil
}
