// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: svc/gateway.proto

package svc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayHttpRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg         string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	FromGateway bool   `protobuf:"varint,3,opt,name=from_gateway,json=fromGateway,proto3" json:"from_gateway,omitempty"`
}

func (x *GatewayHttpRsp) Reset() {
	*x = GatewayHttpRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayHttpRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayHttpRsp) ProtoMessage() {}

func (x *GatewayHttpRsp) ProtoReflect() protoreflect.Message {
	mi := &file_svc_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayHttpRsp.ProtoReflect.Descriptor instead.
func (*GatewayHttpRsp) Descriptor() ([]byte, []int) {
	return file_svc_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayHttpRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GatewayHttpRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GatewayHttpRsp) GetFromGateway() bool {
	if x != nil {
		return x.FromGateway
	}
	return false
}

var File_svc_gateway_proto protoreflect.FileDescriptor

var file_svc_gateway_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x76, 0x63, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x76, 0x63, 0x22, 0x59, 0x0a, 0x0e, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x48, 0x74, 0x74, 0x70, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x47, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x42, 0x17, 0x5a, 0x15, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x76, 0x63, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_gateway_proto_rawDescOnce sync.Once
	file_svc_gateway_proto_rawDescData = file_svc_gateway_proto_rawDesc
)

func file_svc_gateway_proto_rawDescGZIP() []byte {
	file_svc_gateway_proto_rawDescOnce.Do(func() {
		file_svc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_gateway_proto_rawDescData)
	})
	return file_svc_gateway_proto_rawDescData
}

var file_svc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_svc_gateway_proto_goTypes = []interface{}{
	(*GatewayHttpRsp)(nil), // 0: svc.GatewayHttpRsp
}
var file_svc_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svc_gateway_proto_init() }
func file_svc_gateway_proto_init() {
	if File_svc_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayHttpRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_svc_gateway_proto_goTypes,
		DependencyIndexes: file_svc_gateway_proto_depIdxs,
		MessageInfos:      file_svc_gateway_proto_msgTypes,
	}.Build()
	File_svc_gateway_proto = out.File
	file_svc_gateway_proto_rawDesc = nil
	file_svc_gateway_proto_goTypes = nil
	file_svc_gateway_proto_depIdxs = nil
}
