// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: svc/review/review.ext.proto

package review

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReviewExtClient is the client API for ReviewExt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewExtClient interface {
}

type reviewExtClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewExtClient(cc grpc.ClientConnInterface) ReviewExtClient {
	return &reviewExtClient{cc}
}

// ReviewExtServer is the server API for ReviewExt service.
// All implementations should embed UnimplementedReviewExtServer
// for forward compatibility
type ReviewExtServer interface {
}

// UnimplementedReviewExtServer should be embedded to have forward compatible implementations.
type UnimplementedReviewExtServer struct {
}

// UnsafeReviewExtServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewExtServer will
// result in compilation errors.
type UnsafeReviewExtServer interface {
	mustEmbedUnimplementedReviewExtServer()
}

func RegisterReviewExtServer(s grpc.ServiceRegistrar, srv ReviewExtServer) {
	s.RegisterService(&ReviewExt_ServiceDesc, srv)
}

// ReviewExt_ServiceDesc is the grpc.ServiceDesc for ReviewExt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReviewExt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svc.user.ReviewExt",
	HandlerType: (*ReviewExtServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "svc/review/review.ext.proto",
}
