// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.0
// source: svc/review/review.int.proto

package review

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserIntClient is the client API for UserInt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserIntClient interface {
	// 接口名称不要过于笼统，这样不便于搜索
	// good：ReviewResource
	// bad: Review
	ReviewResource(ctx context.Context, in *ReviewResourceReq, opts ...grpc.CallOption) (*ReviewResourceRes, error)
}

type userIntClient struct {
	cc grpc.ClientConnInterface
}

func NewUserIntClient(cc grpc.ClientConnInterface) UserIntClient {
	return &userIntClient{cc}
}

func (c *userIntClient) ReviewResource(ctx context.Context, in *ReviewResourceReq, opts ...grpc.CallOption) (*ReviewResourceRes, error) {
	out := new(ReviewResourceRes)
	err := c.cc.Invoke(ctx, "/svc.user.UserInt/ReviewResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserIntServer is the server API for UserInt service.
// All implementations should embed UnimplementedUserIntServer
// for forward compatibility
type UserIntServer interface {
	// 接口名称不要过于笼统，这样不便于搜索
	// good：ReviewResource
	// bad: Review
	ReviewResource(context.Context, *ReviewResourceReq) (*ReviewResourceRes, error)
}

// UnimplementedUserIntServer should be embedded to have forward compatible implementations.
type UnimplementedUserIntServer struct {
}

func (UnimplementedUserIntServer) ReviewResource(context.Context, *ReviewResourceReq) (*ReviewResourceRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewResource not implemented")
}

// UnsafeUserIntServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserIntServer will
// result in compilation errors.
type UnsafeUserIntServer interface {
	mustEmbedUnimplementedUserIntServer()
}

func RegisterUserIntServer(s grpc.ServiceRegistrar, srv UserIntServer) {
	s.RegisterService(&UserInt_ServiceDesc, srv)
}

func _UserInt_ReviewResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewResourceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserIntServer).ReviewResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svc.user.UserInt/ReviewResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserIntServer).ReviewResource(ctx, req.(*ReviewResourceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserInt_ServiceDesc is the grpc.ServiceDesc for UserInt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserInt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "svc.user.UserInt",
	HandlerType: (*UserIntServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReviewResource",
			Handler:    _UserInt_ReviewResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc/review/review.int.proto",
}
